name: Deploy #Name of the Workflow

on:
  push:
    branches:
    - feature/deploy

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:  
          node-version: '20'
      - name: Configure AWS Credentials  
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: npm install
        env:
          CI: true
        run: |
          npm ci 
      - name: deploy
        run: |
          mv aws-lambda/index.js index.mjs

          zip -r deploy.zip index.js server.js src/ node_modules
          aws lambda update-function-code --function-name=${{secrets.AWS_LAMBDA_NAME}} --zip-file=fileb://deploy.zip 